[build]
  functions = "netlify/functions"

[functions]
  directory = "netlify/functions"

# 스케줄링 설정 - 매시간 실행
[functions."scheduled-news"]
  schedule = "0 * * * *"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200 